"""widen username column

Revision ID: 53300469dafd
Revises: 682a1dbf879d
Create Date: 2026-09-03 15:28:34.008942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53300469dafd'
down_revision: Union[str, Sequence[str], None] = '682a1dbf879d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'username',
#                existing_type=sa.VARCHAR(length=50),
#                type_=sa.String(length=100),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'username',
#                existing_type=sa.String(length=100),
#                type_=sa.VARCHAR(length=50),
#                existing_nullable=False)
#     # ### end Alembic commands ###
    
def upgrade():
    #  Sqlite do not support altering columns' type directly, so we use batch_alter_table to handle this.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('username',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=100),
                              existing_nullable=False)

def downgrade():
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('username',
                              existing_type=sa.String(length=100),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)
